<?php

function shanti_kmaps_importer_menu() {
  return array(
    'shanti_kmaps_importer/test/%' => array(
      'page callback'     => 'shanti_kmaps_importer_test',
      'type'              => MENU_CALLBACK,
      'page arguments'    => array(2),
      'access arguments'  => array('access content'),
			'delivery callback' => 'shanti_kmaps_importer_plaintext_deliver',
    ),
  );
}

function shanti_kmaps_importer_test ($domain) {
	if ($domain != 'subjects' and $domain != 'places') {
		return "Bad domain: '$domain'. Must be either 'subjects' or 'places'.";
	}
	$url = variable_get("shanti_kmaps_admin_server_".$domain);	
	$xml = simplexml_load_string(file_get_contents("$url/features/nested.xml"));
	$out = '';
	foreach ($xml->xpath('//feature') as $f) {
		$id 						= $f->attributes()->id;
		$title 					= trim($f->attributes()->title); 
		$parent_name		= null;
		foreach ($f->xpath('parent::*[@id]') as $p) {
			$parent_id			= $p->attributes()->id;
			$parent_title 	= trim($p->attributes()->title);
			$parent_name 		= "$parent_title ($domain-$parent_id)";		
		}
		$out 						.=  "$title ($domain-$id)|$parent_name|$id\n";
	}
	return $out;
}

function shanti_kmaps_importer_plaintext_deliver($page_callback_result) {
  drupal_add_http_header('Content-Type', 'text/plain; utf-8');
	print $page_callback_result;
}

